@startuml

title White class diagram

/'!pragma ratio 0.5
allow_mixing
'/

!include users.package.puml
!include shops.package.puml
!include discounts.package.puml
!include purchases.package.puml
!include baskets.package.puml


/'
package notifications
package dm
package reviews
package reports
'/


@enduml