@startuml

skin rose

title Architecture Diagram

package "Communication" {
}

package "Service" {
    component [service]
}

package "Domain"{
  component [Users]
  component [Notifications]
  component [Shops]
  component [Market]
}

package "DataAccessLayer"{

}

package "Storage"{

}

cloud "External API" as API{
  component [Payment Service]
  component [Delivery Service]
} 


Service -down-> Domain
Communication -down-> Service
Domain -down-> DataAccessLayer
DataAccessLayer -down-> Storage

Users --o Market

Market --o Shops
Market --o Notifications


Domain -down-> API


@enduml